set export

# Configure shell for Windows
set windows-shell := ["pwsh", "-NoLogo", "-Command"]

# Lists all targets
[private]
default:
  @just --list

# Test dotslash feature with automated test located at devcontainer-features/test/dotslash/test.sh.
[group('Development Container Feature')]
test-feature-autogenerated:
  #!/usr/bin/env bash
  set -euo pipefail

  base_images=(
    debian:latest
    mcr.microsoft.com/devcontainers/base:ubuntu
    ubuntu:latest
  )

  for base_image in ${base_images[@]}; do
    devcontainer features test \
      --base-image debian:latest \
      --features dotslash \
      --project-folder devcontainer-features \
      --skip-scenarios
  done

# Test dotslash feature with scenarios defined in devcontainer-features/test/dotslash/scenarios.json.
[group('Development Container Feature')]
test-feature-scenarios:
  #!/usr/bin/env bash
  set -euo pipefail

  devcontainer features test \
    --features dotslash \
    --project-folder devcontainer-features \
    --skip-autogenerated \
    --skip-duplicated

# Check Python package
[group('Downstream')]
[working-directory: 'python']
python-check:
  uvx ruff check
  uvx ruff format --check --diff

# Fix Python package
[group('Downstream')]
[working-directory: 'python']
python-fix:
  uvx ruff check --fix
  uvx ruff format

# Test Python package
[group('Downstream')]
[working-directory: 'python']
python-test DOTSLASH_VERSION="latest":
  uv run --reinstall --isolated --no-editable --with pytest pytest

# Build Python distributions
[group('Downstream')]
[working-directory: 'python']
python-build DOTSLASH_VERSION="latest":
  uv build
