FROM ghcr.io/astral-sh/ruff as ruff

FROM mcr.microsoft.com/devcontainers/rust:bookworm

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 --from=ruff /ruff /usr/local/bin/ruff
