---
name: Development Container-Based CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.runsOn }}
    strategy:
      matrix:
        runsOn:
          - ubuntu-24.04-arm
          - ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      - if: ${{ github.event_name != 'pull_request' }}
        id: cache_to_helper
        run: echo "cacheTo=ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash" >> $GITHUB_OUTPUT
      - name: Build devcontainer image
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash
          cacheTo: ${{ steps.cache_to_helper.outputs.cacheTo }}
          env: |
            CI=1
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash
          push: filter
          refFilterForPush: refs/heads/main

  test-devcontainer-feature-autogenerated:
    needs: build
    runs-on: ${{ matrix.runsOn }}
    strategy:
      matrix:
        runsOn:
          - ubuntu-24.04-arm
          - ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash
          push: never
          runCmd: just test-feature-autogenerated

  test-devcontainer-feature-scenarios:
    needs: build
    runs-on: ${{ matrix.runsOn }}
    strategy:
      matrix:
        runsOn:
          - ubuntu-24.04-arm
          - ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainers/dotslash
          push: never
          runCmd: just test-feature-scenarios
