---
name: Testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-devcontainer-feature:
    runs-on: ${{ matrix.runsOn }}
    strategy:
      matrix:
        runsOn:
          - ubuntu-24.04-arm
          - ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: "true"
          base-path-to-features: ./devcontainer-features/src
